export const KPI_THRESHOLDS = {
  EXCELLENT: 90,
  ON_TRACK: 70,
  AT_RISK: 50,
  BELOW_THRESHOLD: 0,
} as const;

export const RETENTION_PERIODS_MONTHS = {
  DROPSHIPPING: 3,
  CONSIGNMENT: 6,
  WHOLESALE: 6,
  IMPORT_EXPORT: 9,
  EXHIBITION: 6,
  AUCTION_BIDDING: 6,
  WHITE_LABEL: 12,
  BRICK_MORTAR: 12,
  PACKAGING: 6,
  DESIGN_COLLABORATION: 6,
  STORYTELLING_MEDIA: 6,
  WAREHOUSE_FULFILLMENT: 9,
  LOGISTICS: 12,
  MUSEUM_INSTITUTIONAL: 12,
  NGO_GOVERNMENT: 12,
  TECHNOLOGY_PARTNERSHIP: 18,
} as const;
